# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 07:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band', models.CharField(default='', max_length=128)),
                ('date', models.DateField()),
                ('city', models.CharField(default='', max_length=128)),
                ('venue', models.CharField(blank=True, default='', max_length=128)),
                ('want_level', models.IntegerField(max_length=5)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
