# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='want_level',
            field=models.IntegerField(),
        ),
    ]
